[meta]
name     = "COTD HUD"
author   = "XertroV"
category = "Race"
version  = "0.1.0"

[script]
dependencies = [ "NadeoServices", "TrackmaniaApiObjsAndHelpers" ]
imports = [ "Permissions.as", "Time.as" ]
#__DEFINES__
# defines = [ "DEV" ]
# defines = [ "DEV", "UNIT_TEST" ]
# defines = [ "UNIT_TEST" ]
# defines = [ "RELEASE" ]
optional_dependencies = [ "BetterChat" ]
