[meta]
name     = "COTD HUD"
author   = "XertroV"
category = "Race"
version  = "0.2.4"

[script]
dependencies = ["NadeoServices"]
#__DEFINES__
# defines = [ "DEV" ]
# defines = [ "DEV", "UNIT_TEST" ]
# defines = [ "UNIT_TEST" ]
# defines = [ "RELEASE" ]
optional_dependencies = [ "BetterChat" ]
